// Generated by CoffeeScript 1.6.3
(function() {
  var cb, interval, lookahead, running;

  running = false;

  lookahead = 25;

  interval = null;

  cb = function(e) {
    switch (e.data) {
      case 'start':
        if (!running) {
          running = true;
          return interval = setInterval(function() {
            return self.postMessage('schedule');
          }, lookahead);
        }
        break;
      case 'stop':
        clearInterval(interval);
        return running = false;
    }
  };

  self.addEventListener('message', cb, false);

}).call(this);
